const PAIRS = [
  [
    {
      heading: "MD CRYPTO-",
      body: `OUR GOLD IS DEFINED BY OUR SYSTEMS OF PRODUCTS AND THE LIFESTYLES IT WILL CREATE FOR GOOD GOVERNMENT WHICH IS THE MD CONCEPT.
OUR GOLD IS GREAT HI-TECH, INTELLIGENT, FLEXIBLE, ALL IN ONE, DURABLE PRODUCTS FOR REAL FREEDOM FOR THE BEST LIFESTYLE -SELFSUFFICIENCY`,
    },
    {
      heading: "CURRENCY - CRYPTO",
      body: `OUR CURRENCEY WILL PROVIDE EVERMORE STABILITY THAN ANY OTHER SYSTEM. ITS NOT BASED ON A USELESS SHINY RARE METAL LIKE GOLD THAT HAS NO OTHER FUNCTION OTHER THAN BEING USED FOR JEWELRY BECAUSE IT IS RARE TO FIND.
OUR CURRENCY OR CRYPTO IS BASED ON GREAT PRODUCTS THAT ARE INTELLIGENT, FLEXIBLE AND DURABLE WHERE MATERIALS CAN BE USED OVER AND OVER TO CREATE AS MANY PRODUCTS AS NEEDED.
CURRENCY WAS INVENTED TO ELIMINATE THE VERY INEFFICIENT SYSTEM OF EXCHANGE CALLED THE BARTER SYSTEM WHEN GOLD WAS NOT AVAILABLE.
I WILL GIVE YOU TWO OF MY COWS FOR 100 POUNDS OF WHEAT.
GOLD IS STILL AROUND BUT NOT ENOUGH SO WE HAVE CREATED PRINTED PAPER OR METAL CURRENCY FOR EXCHANGE THAT IS UNFORTUNATELY STILL MOSTLY BASED ON GOLD EVEN THOUGH WE WENT OFF THE GOLD STANDARD YEARS AGO.
BUT STILL THERE IS NOT ENOUGH REAL COLLATERAL, FUNCTIONAL PRODUCTS TO DEPEND ON WHERE NOW IT HAS BECOME MOSTLY FINANCIAL PRODUCTS WHERE IT IS FINANCING OTHER FINANCING AND MORE FINANCING, FINANCING MORE FINANCING AND ON AND ON. IT RESEMBLES AN UPSIDE DOWN PYRAMID SCHEME WHERE THERE IS ONLY VERY LITTLE COLATERAL AT THE BOTTOM AND A HUGE AMOUNT OF FINANCING AT THE TOP.
NOW WE FINALLY HAVE A SYSTEM OF GREAT PRODUCTS MADE BY MD TO REPRESENT GOLD, OUR ECONOMY AND OUR FINAL ALL IN ONE SIMPLE HI-TECH LIFESTYLE.`,
    },
  ],
  [
    {
      heading:
        "GOVERNMENT, VOTING, PEOPLE IN CHARGE AND HOW THEY BECOME IN CHARGE AND WHAT WE SHOULD CHANGE",
      body: `CIVILIZATION IS DEFINED BY ITS ABILITY TO CREATE AND IMPROVE ITS PRODUCTS TO REDUCE INEFFICIENCY, CONFLICT AND SUFFERING AND ALLOW MORE OF WHAT THE FOUNDING FATHERS DESCRIBED, THE PURSUIT OF HAPPINESS. NOT HOW WE RAISE TAXES AND REDISTRIBUTE THEM TO THE COMPLAINERS (OR MOST COMPLAINERS) . POLITICIANS IN ESSENENCE ARE COMPLAINT AND TAX MANAGERS. THIS IS WHY THEY CONSTANTLY EMPHASIZE AND BRAG ABOUT THEIR ABILITY OF LEADERSHIP AND PROMISES OF RAISING STANDARDS FOR EVERYONE WITH THEIR SCARY WORDS CREATING CAUSES TO BLAME THE OTHER SIDE. IN THE BEGINNING AND FORMATION OF THIS COUNTRY WE NEEDED REPRESENTATIVES POLITICIANS TO MEET, GATHER AND DISCUSS ALL ISSUES THEY WERE CONFRONTED WITH IN ONE PERMANENT LOCATION BECAUSE THEY DIDN'T HAVE AUTOMOBILES, AIRPLANES, TELEPHONES OR ANY OTHER WIRELESS COMMUNICATIONS. THEY NEEDED PEOPLE TO MAN THE FORT AND MAKE QUICK SERIOUS DECISIONS WHEN NECESSARY. ALL THEY HAD WAS A HORSE AND BUGGY TO TRAVEL AND GATHER. 250 YEARS LATER WE HAVE ALL THE HI-TECHNOLOGY AVAILABLE FOR LIVING COMFORTABLY, INTERNET, WIRELES COMMUNICATION, AIRPLANES, AUTOMOBILES, AI MULTIFUNCTIONAL AND FLEXIBLE AS WELL AS DURABLE APPLIANACES AND PRODUCTS.
BUT OUR SYSTEM OF VOTING IS STILL THE SAME. ITS OUTDATED. SOMEONE ELSE WILL ALWAYS MAKE ALL THE DECISIONS DESPITE ALL THAT TECHNOLOGY. THE REPRESENTATIVES.`,
    },
    {
      heading: "REPRESENTATIVES",
      body: `REPRESENTATIVES WILL PLAY MOSTLY THE ROLE OF ADVISERS AND PUBLIC ADVOCATES TO ADVISE AND HELP PEOPLE CREATE LAWS THAT ARE NEEDED OR NEED TO BE REVISED WHICH IS WHAT THEY WERE MEANT TO BE IN THE BEGINNING. HELPING THE PUBLIC ATTAIN WHAT THEY NEED IN THEIR COMMUNITIES, NOT WHAT AMBITIOUS REPRESENTATIVES NEED OR WANT IN LIFE WITH THEIR SLICK PROMISES THAT RARELY COME TRUE .
WE DON'T HAVE TO WORRY ABOUT TERM LIMITS ANYMORE
MY FATHER USED TO SAY A BENEVOLENT DICTATOR WHO LOVES HIS COUNTRY IS BETTER THAN THE INEFFICIENCY OF CHECKS AND BALANCES OF DEMOCRTAIC GOVERNMENT
BUT WE DON'T HAVE TO WORRY ABOUT THAT NOW. WHAT IS EFFICIENT, FAIR AND JUST IS WHEN EVERYONE DECIDES ON AS MANY ISSUES AS POSSIBLE.
IF PEOPLE WANT CHANGES THEY HAVE TO PARTICIPATE IN THE DECISION MAKING PROCESS.
THEY MIGHT NOT EVEN MIND VOLUNTEERING TO ATTAIN THOSE CHANGES. CHARITIES AND DOGOODERS DO ITALL THE TIME.`,
    },
  ],
  [
    {
      heading: "CONGRESS- OUTDATED SYSTEM",
      body: `OUR SYSTEM OF GOVERNMENT WAS BASED AND DESIGNED FOR THE NUMBER OF PEOPLE IN THE COUNTRY, OUR POPULATION. THE CENSUS PLAYS A VERY IMPORTANT ROLE. EACH ELECTED OFFICIAL REPRESENTS A DISTRICT WITH CERTAIN BOUNDARIES DETERMINED BY A PARTY COMMITTEE. THIS IS WHY REDISTRICTING IS IMPORTANT WHEN POPULATIONS CHANGE AND PEOPLE AND THEIR IDEAS CHANGE WHERE POLITICIANS AND REPRESENTATIVES ARE CONSTANTLY READJUSTING BOUNDARIES COMPOSED OF THE RIGHT TYPE OF POPULATION TO BENEFIT THEIR ISSUES IN ORDER TO BE ELECTED.
HOUSE OF REPRESENTATIVES AND SENATE AT THE FEDERAL AND STATE LEVEL HAVE ONE PURPOSE. TO REPRESENT PEOPLE BUT TO BE FAIR, SINCE IT IS BASED ON POPULATION IF CERTAIN STATES OR DISTRICTS ARE MORE POPULATED, IN ORDER TO MAKE UP FOR THE LESSER POPULATED AREAS THE SENATE HAS THE SAME NUMBER OF VOTES NO MATTER DESPITE WHAT THE HOUSE MAJORITY TO OFFSET THE BALANCE.
DO WE NEED TO WORRY ABOUT ALL THAT ALL THAT IF WE ALL WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, LIFESTYLE AND PRODUCTS STANDS FOR.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES SINCE YOU KNOW MORE ABOUT YOUR PROBLEMS THAN SOMEONE SOMEWHERE ELSE IN THE COUNTRY.
IF WE WANT CHANGES THAT BAD WE NEED PEOPLE TO BE APART OF THE DECISION MAKING PROCESS.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY AND PRODUCTS STANDS FOR.`,
    },
    {
      heading: "PARTY AFFILIATION",
      body: `THERE IS NOTHING IN THE CONSTITUTION THAT STATES THAT THERE HAS TO BE PARTIES CREATED AND MEMBERSHIP IS NECESSARY IN A PARTY IN ORDER TO BE ELECTED. THAT'S WHY THEY HAVE INDEPENDENT PARTIES. PARTIES WERE CREATED TO RAISE MONEY. THE BIGGER THE PARTY THE MORE POTENTIAL TO RAISE CAMPAIGN FINANCING. THAT'S WHY YOU HAVE TO THINK LIKE THE REST OF THE PARTY IF YOU WANT TO TAP INTO THAT AVAILABLE FINANCING. WHAT HAPPENED TO ONLY REPRESENTING THE PEOPLE IN YOUR DISTRICT AND WHAT THEY WANT. THAT'S NOT GOOD REPRESENTATION.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
  ],
  [
    {
      heading: "PLEBISCITE",
      body: `A PLEBISCITE IS A PRE-ROMAN TERM 2500 YEARS AGO WHERE EVERYONE DECIDED AND VOTED ON AN ISSUE ESPECIALLY WHEN AN EMPEROR OR LEADER WASN'T SURE HOW TO DECIDE ON THAT PARTICULAR ISSUE.
MANY COURTS AROUND THE WORLD HAVE 3 JUDGES AND 6-15 JURORS IN THEIR COURTS.
SOME OF THE PEOPLE INVOLVED IN THE FORMATION OF OUR DEMOCRATIC SYSTEM OF GOVERNMENT BELIEVED THAN EVEN REPRESENTATIVES WERE NOT DEMOCRATIC ENOUGH STATING THAT WE ARE NOW REPLACING KINGS AND QUEENS WITH MORE KINGS AND QUEENS.
THE MORE PEOPLE DECIDING THE MORE FAIR THE SYSTEM IS.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY AND PRODUCTS STANDS FOR.`,
    },
    {
      heading: "SELF SUFFICIENCY-",
      body: `WE DON'T ALWAYS HAVE TO UNITE TO GATHER ENOUGH VOTES TO GET WHAT WE NEED WHEN WE HAVE GREAT AI PRODUCTS THAT CAN PROVIDE WHAT WE NEED. WE CAN DISAGREE, NOT ACCEPT EVERYTHING AND STILL GET ALONG NOW WITH MD LIFESTYLE AND PRODUCTS.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, LIFESTYLE AND PRODUCTS STANDS FOR.`,
    },
  ],
  [
    {
      heading: "VOTER SOFTWARE",
      body: `OUR VOTER SOFTWARE THAT WE ARE DEVELOPING WILL MAKE IT EASIER TO VOTE RIGHT IN THE COMFORT OF YOUR OWN HOME JUST BY USING YOUR COMPUTER AND OUR UNIQUE HI-TECH FRAUD PROOF WEBSITE. NO WORRIES ABOUT IDENTITY OR ILLEGAL VOTERS TO INSURE ELECTED OFFICIALS OR REPRESENTATIVES OR ADVISERS ARE ELECTED WITH THE CORRECT NUMBER OF VOTES.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, LIFESTYLE AND PRODUCTS STANDS FOR.`,
    },
    {
      heading: "TAXATION-",
      body: `GOVERNMENTS COLLECT TAXES TO PAY FOR THE EXPENSES OF RUNNING THE GOVERNMENT AGENCIES- INFRASTRUCTURE-TRANSPORTATION, NATIONAL DEFENSE MILITARY, EDUCATION AND HEALTH FACILITIES, SOCIAL SECURITY /MEDICARE, ADMINISTRATION OF JUSTICE- COURTS, DEBT ON INTEREST IN BORROWED MONEY FROM TREASURIES.
IF COLLECTED TAXES (INCOME, PROPERTY AND OTHER TAXES AND TREASURIES (BORROW MONEY BY SELLING TREASURIES TO PUBLIC) ARE NOT ABLE TO PAY FOR THESE EXPENSES THEN THE GOVERNMENT PRINTS MONEY WHICH REDUCES THE VALUE OF THEIR CURRENCY.
THE FEDERAL RESERVE WAS CREATED TO HELP PROVIDE MORE BANKING AND LOANS FOR THE PUBLIC CREATING ITS OWN FED FUNDS RATE TO BANKS BORROWING FROM IT.
THE FED FUNDS RATE IS USED BY GOVERNMENTS TO ALLOW MORE BANKING WHERE BANKS CAN BORROW MONEY FROM THE FED TO SATISFY THE REQUIRED RESERVE BANKS ARE REQUIRED TO MAINTAIN IN CASE THERE IS A SUDDEN DOWNTURN IN THE ECONOMY AND PEOPLE DEMAND THEIR MONEY.
IN ADDITIONTHE FDIC INSURANCE WAS CREATED BY THE GOVERNMENT TO PROMOTE BANKING BY INSURING THAT DEPOSITERS ARE GUARANTEED UP TO 250,000 OF THEIR MONEY IN CASE A BANK COLLAPSES.
OR SOME PEOPLE BELIEVE THAT WE CAN LET THE MARKET DECIDE WITHOUT THE FED ALWAYS INTERFERING AND LEADING THEM ON.`,
    },
  ],
  [
    {
      heading: "INVESTING-",
      body: `WHAT CONCEPTS IMPACT THE ECONOMY THE MOST WHEN INVESTING'
-SUPPLY AND DEMAND. MORE DEMAND IS HIGHER PRICES
-INFLATION- LESS PRODUCTS, MORE DEMAND CREATES HIGHER PRICES
-INCENTIVE TO BUY AND PRICING-
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
    {
      heading: "INFRASTRUCTURE",
      body: `WE HAVE BEEN FLYING FOR 123 YEARS WITH GREAT NAVAIGATIONAL SYSTEMS TO GUIDE US BUT WE ARE STILL BUILDING ROADS, BRIDGES, TUNNELS, SUBWAYS, TRAIN TRACKS, SIDEWALKS, GUARDRAILS, POLES AND SIGNS BUT ALSO THE COST OF MAINTAINING THEM FOREVER. THE AMOUNT OF TAXES THAT CAN BE SAVED IS IN THE QUADRILLIONS THAT COULD HELP DEVELOP OTHER PARTS OF SOCIETY. PUBLIC TRANSPORTAION CAN BE EASILY CONVERTED TO TRAVEL FROM VACANT LOT TO ANOTHER OR ROFTOP TO ROOF TOP.
GOVERNMENTS MAIN FUNCTION HAS ALWAYS BEEN ROADS AND THE MILITARY FOR DEFENSE.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, LIFESTYLE AND PRODUCTS STANDS FOR.`,
    },
  ],
  [
    {
      heading: "HEALTH",
      body: `PREVENTATIVE MEDECINE
-DO NOT WAIT UNTILL YOU FALL OVER TO SEE A DOCTOR. OBTAIN A FULL PROFILE BLOOD TEST WHICH INCLUDES - COMPLETE BLOOD COUNT A CBC AND A COMPREHENSIVE METABOLIC PANEL A CMP AND DISPLAYS ALL THE CHEMICALS IN YOUR BODY TO INSURE EVERYTHING IS NORMAL LEVEL EVERY 6 MONTHS. MOST INSURANCES PAY FOR THIS.
- REQUEST AN MRI OR CT SCAN, OR XRAY IF YOU FEEL YOU NEED AN IN-DEPTH ACCURATE ANALYSES. DEMAND IT IF YOU FEEL SOMETHING IS WRONG. ITS YOUR MONEY AND LIFE.
LEARN TO READ THESE RESULTS. THEY NORMALLY STATE WHETHER IT IS NORMAL OR NOT BUT U CAN OBTAIN INFO ON THE INTERNET AS WELL. ASK A SEARCH ENGINE.
DON'T BE AFRAID TO ASK QUESTIONS TO THE DOCTOR TO EXPLAIN THE TEST OR IMAGES . KEEP A COPY OF EACH TEST FOR COMPARISON.
ITS YOUR MONEY AND YOUR LIFE.
-DIET- YOU DON'T HAVE TO EAT A LOT TO STOP CRAVINGS. EAT THE RIGHT FOODS. NUTS ARE ALWAYS GOOD FOR STOPPING CRAVING.
-TAKE CARE OF THE MOST IMPORTANT ORGAN IN YOUR BODY. THE CIRCULATORY SYSTEM WHICH DELIVERS ALL THE NUTRIENTS, HORMONES, ENZYMES AN ALL THE OTHER NECESSARY INGREDIENTS THAT TAKE CARE OF ALL YOUR ORGANS.
MAKE SURE YOU KEEP IT OPEN AND CLEAN ELIMINATING ALL PLAQUE OR ELSE EACH ORGAN WILL DETERIORATE ONE BY ONE. ONE WAY IS TO EXERCISE REGULARLY WHERE THE BLOOD FLOW WILL PRESSURE WASH THE INSIDES OF YOUR BLOOD VESSELS ELIMINATING ANY CLOGS.
-THIS WILL LEAD TO A FASTER MORE EFFICIENT AND HEALTHIER METABOLASM
NATURES PURPOSE IS ONLY TO RECYCLE EVERYTHING. IF THE BASICS, THE DNA OR THE SOFTWARE OF LIFE CAN BE CONTROLLED AND MANIPULATED WE WILL ALL LIVE LONGER. NO DISEASES, PLENTY OF FOOD AND HOUSING THAT CAN BE EASILY PRODUCED WITH ONE ALL IN ONE MATERIALS
WHAT IS HEALTH ANYWAY. FOOD AND SHELTER AND SOME ENTERTAINMENT FOR OUR FREE TIME. WE DON'T NEED TO EAT MORE FOOD OR HAVE BIGGER HOUSING TO SATISFY OUR EGOS. GOVERNMENT MEDICARE AND MEDICAID INSURANCE THAT WE PAY FOR SHOULD KNOW THIS. MAYBE WE SHOULD GIVE THAT MONEY DIRECTLY TO THE PEOPLE AND LET THEM DECIDE AND PAY FOR THEIR INSURANCE.
THAT'S PREVENTATIVE MEDECINE AND THAT'S MD LIFESTYLE . WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
    {
      heading: "EDUCATION",
      body: `ONLY ONE CATEGORY OF KNOWLEDGE- SCIENCE PHYSICS, CHEMISTRY, BIO ENG ARCH . THATS WHAT EDUCATION USED TO BE. EVEN ART REQUIRED SCIENCE FOR CREATING COLORS, CANVAS, CARVING TOOLS AND STONEWORK
EVERYTHING ELSE IS LIFES LIVING ENTERTAINMENT . DON'T WASTE YOUR EDUCATION OR YOU WILL BE STUCK WITH IT FOREVER. 4 YEARS WILL TAKE YOU THRU 40 YEARS OF JOBS OR 40 YEARS OF UNCERTAINTY, LESS INCOME AND THE INABILITY TO EARN A GOOD LIVING. PEOPLE GO TO SCCHOOL TO LEARN WHETHER THEY ARE GOOD AT COMPREHENDING CERTAIN TOPICS OR NOT. YOU ARE THEIR TO LEARN. THAT'S ALL YOU NEED TO KNOW.
EDUCATORS ADD SCIENCE TO SOCIOLGY TO SOUND LIKE YOU CAN COMPETE AND SCHOOLS CAN GET THEIR TUITION INSTEAD OF FLUNKING OUT WITH REAL SCIENCE .
PEOPLE WITH HIGHER LEVEL OF EDUCATION AS IN THE SCIENCES FEEL WE ARE CREATING USELESS PEOPLE WHO CANT DO ANYTHING BUT COMPLAIN. ITS BAD ENOUGH THEY WONT HAVE TO DO MUCH IN FUTURE WITH MACHINES, ROBOTICS AND AI TO DO THEIR WORK AND THINKING. STUDENT LOANS TO SOME SUBJECTS SHOULD BE CONTROLLED OR ELIMINATED. IN JAPAN AND OTHER COUNTRIES THEY HAVE ELIMINATED COURSES LIKE HUMANITIES AND SOCIOLGY FROM SCHOOLS.
THE MANY PEOPLE WITH THESE TYPES OF LESS ADVANCED OR LESS KNOWLEDGABLE DEGREES HAVE ACQUIRED A DIFFERENT TYPE OF TALENT. INTERROGATIONAL SKILLS WITH GOOGLE OR ANOTHER SEARCH ENGINE TO VERIFY THEIR VICTIMS AND SHOW OFF THEIR KNOWLEDGE. LAWYERS ARE VERY GOOD AT THAT. THEY DON'T NEED TO KNOW THE EVIDENCE THEMSELVES THAT THEY ARE SEEKING JUST THE ABILITY TO QUESTION A WITNESS IF THEY KNOW WITH AN EXPERT WITNESS TO BACK HIM UP.
AGAINNATURES PURPOSE IS TO RECYCLE EVERYTHING. TEMPERATURE CONTROLS ALL THOSE ELEMENTS THAT WAS CREATED IN NATURE WHERE ALL THOSE REACTIONS OCCUR WHEN THE TEMPERATURE CHANGES- COLD AND HOT- 3 STATES OF MATTER, SOLID, LIQUID, GAS.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
  ],
  [
    {
      heading: "LAWS-AND CRIME-",
      body: `JUST LAWS AND PUNISHMENT TO DISSUADE CRIME BUT ALSO PROMOTE THE DEVELOPMENT OF A SOCIETY OF THE FUTURE. IF EVERYONE HAS EVERYTHING THEY NEED, WHAT KIND OF CRIME CAN WE HAVE. TOO MUCH LOVE. FOOD AND SHELTER IS THE BASICS OF HUMANITIES SURVIVAL. WE DON'T NEED MORE FOOD OR BIGGER HOUSING.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
    {
      heading: "MILITARY",
      body: `A STRONG MILITARY TO PREVENT ANY FOREIGN INTERVENTION OR ATTACKS.
WE WANT YOU TO DECIDE ON MOST OF OUR ISSUES. THAT'S WHAT THE YOU DECIDE PARTY AND ITS MD CURRENCY, PRODUCTS AND LIFESTYLE STANDS FOR.`,
    },
  ],
];

function BodyText({ text }) {
  return (
    <div className="mt-3 space-y-3 text-sm leading-relaxed text-neutral-800 sm:text-[0.9375rem]">
      {text.split("\n").map((line, i) => (
        <p key={i}>{line}</p>
      ))}
    </div>
  );
}

export default function GovTextAdditionSection() {
  return (
    <section
      id="md-government-text"
      className="w-full scroll-mt-24 border-t border-neutral-100 bg-white py-14 sm:py-20"
    >
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <h2 className="text-center text-xl font-black uppercase tracking-tight text-neutral-900 sm:text-3xl lg:text-4xl">
          Proposed MD Systems of Lifestyle &amp; Products That Define
          Government, Its Currency and the Overall MD Concept for Changes
        </h2>
        <p className="mx-auto mt-4 max-w-4xl text-center text-sm font-bold uppercase leading-relaxed tracking-wide text-neutral-700 sm:text-base">
          GOVERNMENT INEFFICIENCIES- OUR VOTING SYSTEM FOR SELECTING OUR
          RULERS, OUR TAXES, CURRENCY, BANKING AND THE ECONOMY, EDUCATION ,
          HEALTH, LAWS AND CRIME
        </p>

        <div className="mt-10 space-y-8 sm:mt-12 sm:space-y-10">
          {PAIRS.map((pair, rowIndex) => (
            <div
              key={rowIndex}
              className="grid gap-6 md:grid-cols-2 md:gap-8 lg:gap-10"
            >
              {pair.map((block) => (
                <article
                  key={block.heading}
                  className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm sm:p-6"
                >
                  <h3 className="border-b border-neutral-200 pb-2 text-base font-black uppercase tracking-wide text-neutral-900 sm:text-lg">
                    {block.heading}
                  </h3>
                  <BodyText text={block.body} />
                </article>
              ))}
            </div>
          ))}
        </div>

        <div className="mt-10 rounded-2xl border border-neutral-200 bg-neutral-50 p-5 text-center sm:mt-12 sm:p-8">
          <p className="text-sm font-bold uppercase leading-relaxed tracking-wide text-neutral-900 sm:text-base">
            MORE PERTINENT INFORMATION ON OUR EXISTING SYSTEMS OF GOVERNMENT,
            CURRENCY, ECONOMY, HEALTH, LAWS AND IF MD LIFESTYLE AND PRODUCTS
            SHOULD CHANGE THEM.
          </p>
          <p className="mt-3 text-sm font-black uppercase tracking-wide text-[#b91c1c] sm:text-base">
            YOU DECIDE
          </p>
        </div>
      </div>
    </section>
  );
}
